name: Build Skia lib from upstream
description:
  从上游仓库编译Skia二进制库文件。
  MacOS上使用Mental
  Linux上使用Vulkan
  Windows上使用Direct3D
  移除对android移动端的支持和XML/DOM相关，禁用FontConfig，以减小最终二进制包的体积
  使用动态链接系统库，以减小最终二进制包体积，但会降低可移植性。


on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref: [main, chrome/m150]
    steps:
      - name: 拉取代码 - ${{ matrix.ref }}
        uses: actions/checkout@v4
        with:
          repository: google/skia
          ref: ${{ matrix.ref }}
          submodules: false

      - name: 安装系统依赖
        run: |
          chmod +x tools/install_dependencies.sh
          sudo ./tools/install_dependencies.sh
          python3 tools/git-sync-deps
        
      - name: 生成构建配置
        run: bin/gn gen out/Release --args='is_debug=false skia_enable_discrete_gpu=false skia_enable_pdf=false skia_enable_gpu=true skia_use_webgl=false skia_use_gl=false is_official_build=true skia_use_crabbyavif=false skia_use_libheif=false skia_use_piex=false skia_use_fontconfig=false target_os="linux" skia_use_libwebp=false skia_use_libwebp_encode=false skia_use_expat=false skia_use_vulkan=true skia_use_fontconfig=false skia_use_metal=false skia_use_direct3d=false'
        
      - name: 编译
        run: ninja -C out/Release
        
      - name: 上传临时编译产物
        uses: actions/upload-artifact@v4
        with:
          name: skia-${{ matrix.ref }}
          path: out/Release/
          retention-days: 7
          
      - name: 设置 Release 标签
        id: set_tag
        run: |
          TAG_NAME="skia-${REF//\//-}"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
        env:
          REF: ${{ matrix.ref }}
          
      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          name: "Built Skia ${{ matrix.ref }} ($(date +'%Y-%m-%d'))"
          files: out/Release/
          generate_release_notes: true
          overwrite: true
