name: 同步上游Skia仓库

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: 完整检出仓库
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 同步Skia仓库
        run: |
          git config --global --add safe.directory /github/workspace
          git remote add upstream https://github.com/google/skia.git
          git fetch upstream --prune
          git push origin --mirror
